# Generated by Django 4.2.16 on 2025-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_organization_and_license_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
