# Generated by Django 4.2.16 on 2025-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_diffreport_hostname_alter_diffreport_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentsettings',
            name='use_cisofy_repo',
            field=models.BooleanField(default=False),
        ),
    ]
