# Generated by Django 4.2.16 on 2026-02-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fix_supported_os_rule_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('enrolled', 'Device Enrolled'), ('deleted', 'Device Deleted'), ('license_changed', 'License Changed'), ('compliance_changed', 'Compliance Status Changed')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ComplianceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliant', models.BooleanField()),
                ('hardening_index', models.IntegerField(blank=True, null=True)),
                ('warning_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_snapshots', to='api.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='api_complia_device__731ed4_idx'), models.Index(fields=['-created_at'], name='api_complia_created_347063_idx')],
            },
        ),
    ]
