# Generated by Django 5.2.11 on 2026-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fix_supported_os_rule_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('enrolled', 'Device Enrolled'), ('deleted', 'Device Deleted'), ('license_changed', 'License Changed'), ('compliance_changed', 'Compliance Status Changed')], db_index=True, max_length=50),
        ),
    ]
