# Generated by Django 5.2.11 on 2026-05-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_deviceevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display (e.g., #3B82F6)', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Custom labels for organizing devices', related_name='devices', to='api.label'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['organization', 'name'], name='api_label_organiz_74e98f_idx'),
        ),
    ]
